# Generated by Django 6.0.6 on 2026-06-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=24, unique=True)),
                ('method', models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('WAVE', 'Wave'), ('CARD', 'Carte bancaire (simulation)')], max_length=24)),
                ('status', models.CharField(choices=[('SUCCESS', 'Reussi'), ('FAILED', 'Echoue')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant (FCFA)')),
                ('payer_phone', models.CharField(blank=True, max_length=30, verbose_name='telephone payeur')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='4 derniers chiffres')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ('-created_at',),
            },
        ),
    ]
