# Generated by Django 6.0.6 on 2026-06-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telephone')),
                ('subject', models.CharField(max_length=180, verbose_name='objet')),
                ('message', models.TextField(verbose_name='message')),
                ('is_processed', models.BooleanField(default=False, verbose_name='traite')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'message de contact',
                'verbose_name_plural': 'messages de contact',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FarmingTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='titre')),
                ('content', models.TextField(verbose_name='conseil')),
                ('theme', models.CharField(blank=True, max_length=120, verbose_name='theme')),
                ('image', models.ImageField(blank=True, null=True, upload_to='public/tips/', verbose_name='image')),
                ('is_published', models.BooleanField(default=True, verbose_name='publie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'conseil agricole',
                'verbose_name_plural': 'conseils agricoles',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('summary', models.TextField(verbose_name='resume')),
                ('content', models.TextField(verbose_name='contenu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='public/news/', verbose_name='image')),
                ('is_published', models.BooleanField(default=True, verbose_name='publiee')),
                ('published_at', models.DateTimeField(verbose_name='date de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'actualite agricole',
                'verbose_name_plural': 'actualites agricoles',
                'ordering': ('-published_at',),
            },
        ),
        migrations.CreateModel(
            name='PlatformInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CoopFaso', max_length=120, verbose_name='nom de la plateforme')),
                ('headline', models.CharField(max_length=220, verbose_name='titre principal')),
                ('presentation', models.TextField(verbose_name='presentation')),
                ('mission', models.TextField(blank=True, verbose_name='mission')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telephone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='public/hero/', verbose_name='image de couverture')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'informations de la plateforme',
                'verbose_name_plural': 'informations de la plateforme',
            },
        ),
    ]
