# Generated by Django 6.0.6 on 2026-06-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True, verbose_name='nom')),
                ('address', models.CharField(max_length=255, verbose_name='adresse')),
                ('phone', models.CharField(max_length=30, verbose_name='telephone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('region', models.CharField(max_length=120, verbose_name='region')),
                ('province', models.CharField(max_length=120, verbose_name='province')),
                ('creation_date', models.DateField(verbose_name='date de creation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cooperative',
                'verbose_name_plural': 'cooperatives',
                'ordering': ('name',),
            },
        ),
    ]
