# Generated by Django 6.0.6 on 2026-06-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='description',
            field=models.TextField(blank=True, verbose_name='presentation'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='visible publiquement'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='location_url',
            field=models.URLField(blank=True, verbose_name='lien de localisation'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='cooperatives/logos/', verbose_name='logo'),
        ),
    ]
