# Generated by Django 6.0.6 on 2026-06-24 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantite recoltee')),
                ('harvest_date', models.DateField(verbose_name='date de recolte')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='prix estimatif (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='members.member', verbose_name='membre')),
            ],
            options={
                'verbose_name': 'production',
                'verbose_name_plural': 'productions',
                'ordering': ('-harvest_date',),
            },
        ),
    ]
