# Generated by Django 6.0.6 on 2026-06-24 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=120, verbose_name='nom')),
                ('first_name', models.CharField(max_length=120, verbose_name='prenom')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1, verbose_name='sexe')),
                ('birth_date', models.DateField(verbose_name='date de naissance')),
                ('phone', models.CharField(max_length=30, verbose_name='telephone')),
                ('address', models.CharField(max_length=255, verbose_name='adresse')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/', verbose_name='photo')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='cooperatives.cooperative', verbose_name='cooperative')),
            ],
            options={
                'verbose_name': 'membre',
                'verbose_name_plural': 'membres',
                'ordering': ('last_name', 'first_name'),
            },
        ),
    ]
