# Generated by Django 6.0.6 on 2026-06-25 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='titre')),
                ('theme', models.CharField(choices=[('SUSTAINABLE', 'Agriculture durable'), ('FERTILIZATION', 'Fertilisation'), ('IRRIGATION', 'Irrigation'), ('PESTS', 'Gestion des ravageurs'), ('HARVEST', 'Techniques de recolte')], max_length=24, verbose_name='theme')),
                ('summary', models.TextField(verbose_name='resume')),
                ('content', models.TextField(verbose_name='contenu du cours')),
                ('document', models.FileField(blank=True, null=True, upload_to='training/documents/', verbose_name='document')),
                ('video_url', models.URLField(blank=True, verbose_name='lien de la video')),
                ('is_published', models.BooleanField(default=True, verbose_name='publie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
            ],
            options={
                'verbose_name': 'cours',
                'verbose_name_plural': 'cours',
                'ordering': ('theme', 'title'),
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='training.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tentative de quiz',
                'verbose_name_plural': 'tentatives de quiz',
                'ordering': ('-completed_at',),
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='question')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='training.course', verbose_name='cours')),
            ],
            options={
                'verbose_name': 'question de quiz',
                'verbose_name_plural': 'questions de quiz',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='reponse')),
                ('is_correct', models.BooleanField(default=False, verbose_name='bonne reponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='training.quizquestion', verbose_name='question')),
            ],
            options={
                'verbose_name': 'choix de reponse',
                'verbose_name_plural': 'choix de reponse',
                'ordering': ('id',),
            },
        ),
    ]
