# Generated by Codex on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_file',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='training/videos/',
                verbose_name='fichier video',
            ),
        ),
    ]
