# Generated by Codex on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_course_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='training/covers/',
                verbose_name='affiche',
            ),
        ),
    ]
