# Generated by Codex on 2026-06-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_course_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='training.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'progression de cours',
                'verbose_name_plural': 'progressions de cours',
            },
        ),
        migrations.CreateModel(
            name='QuizProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('current_index', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Termine')], default='IN_PROGRESS', max_length=16)),
                ('score', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_progress_records', to='training.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'progression de quiz',
                'verbose_name_plural': 'progressions de quiz',
            },
        ),
        migrations.AddConstraint(
            model_name='courseprogress',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_course_progress_per_user'),
        ),
        migrations.AddConstraint(
            model_name='quizprogress',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_quiz_progress_per_user'),
        ),
    ]
