# Generated by Django 6.0.6 on 2026-06-25 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=24, unique=True)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'En attente de paiement'), ('PAID', 'Payee'), ('PROCESSING', 'En preparation'), ('DELIVERED', 'Livree'), ('CANCELLED', 'Annulee')], default='PENDING_PAYMENT', max_length=24)),
                ('delivery_address', models.CharField(max_length=255, verbose_name='adresse de livraison')),
                ('phone', models.CharField(max_length=30, verbose_name='telephone')),
                ('notes', models.TextField(blank=True, verbose_name='instructions')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='montant total (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='client')),
            ],
            options={
                'verbose_name': 'commande',
                'verbose_name_plural': 'commandes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120, verbose_name='nom du produit')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='prix unitaire (FCFA)')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantite')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='sous-total (FCFA)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.order', verbose_name='commande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'ligne de commande',
                'verbose_name_plural': 'lignes de commande',
                'ordering': ('id',),
            },
        ),
    ]
