# Generated by Codex on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcategory_product_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(
                choices=[
                    ('unite', 'unite(s)'),
                    ('kg', 'kg'),
                    ('t', 'tonne(s)'),
                    ('sac', 'sac(s)'),
                    ('L', 'litre(s)'),
                    ('panier', 'panier(s)'),
                ],
                default='unite',
                max_length=20,
                verbose_name='unite',
            ),
        ),
    ]
